name: playsong
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  app_links:
  connectivity_plus:
  flutter_hooks:
  audio_service:
  flip_card:
  audiotagger:
    git:
      url: https://github.com/Sangwan5688/Audiotagger
      ref: 90f2db5
  cached_network_image:
  dart_des:
  device_info_plus:
  file_picker:
  flutter_archive:
  flutter_lyric:
  flutter_displaymode:
  home_widget:
  flutter_localizations:
    sdk: flutter
  intl:
  get_it:
  hive:
  hive_flutter:
  html_unescape:
  just_audio:
  logging:
  marquee:
  material_design_icons_flutter:
  on_audio_query:
  package_info_plus:
  palette_generator:
  path_provider:
  permission_handler:
  persistent_bottom_nav_bar:
    git:
      url: https://github.com/Sangwan5688/PersistentBottomNavBar
      ref: ecdadb0
  # receive_sharing_intent: ^1.4.5
    # Switch back to regular package once https://github.com/KasemJaffer/receive_sharing_intent/issues/256 is resolved
  # receive_sharing_intent:
  sizer:
  salomon_bottom_bar:
  share_plus:
  sliding_up_panel:
  metadata_god: ^0.5.2+1
  url_launcher:
  workmanager:
  uuid:
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  youtube_explode_dart:
  country_icons: ^2.0.2
  country_flags: ^2.2.0
  # receive_sharing_intent:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_icons:
 image_path: "assets/images/app_icon.png"
#  adaptive_icon_foreground: "assets/images/app_icon.png"
 android: true
 ios: true
 remove_alpha_ios: true
#  adaptive_icon_background: "#000000"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Milliard
      fonts:
        - asset: assets/fonts/Milliard-Book-DEMO.otf
        # - asset: fonts/Rene Bieder - Milliard Book Italic DEMO.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
