class CountryCodes {
  static const Map<String, String> countryCodes = {
    'Argentina': 'ar',
    'Austria': 'at',
    'Australia': 'au',
    'Belgium': 'be',
    'Bulgaria': 'bg',
    'Bolivia': 'bo',
    'Brazil': 'br',
    'Canada': 'ca',
    'Chile': 'cl',
    'Colombia': 'co',
    'Costa Rica': 'cr',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Dominican Republic': 'do',
    'Ecuador': 'ec',
    'Estonia': 'ee',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Finland': 'fi',
    'France': 'fr',
    'Germany': 'de',
    'Greece': 'gr',
    'Guatemala': 'gt',
    'Hong Kong': 'hk',
    'Honduras': 'hn',
    'Hungary': 'hu',
    'Indonesia': 'id',
    'Ireland': 'ie',
    'Israel': 'il',
    'India': 'in',
    'Iceland': 'is',
    'Italy': 'it',
    'Japan': 'jp',
    'Korea': 'kr',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Latvia': 'lv',
    'Morocco': 'ma',
    'Mexico': 'mx',
    'Malaysia': 'my',
    'Nicaragua': 'ni',
    'Nigeria': 'ng',
    'Netherlands': 'nl',
    'Norway': 'no',
    'New Zealand': 'nz',
    'Panama': 'pa',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Paraguay': 'py',
    'Romania': 'ro',
    'Russian Federation': 'ru',
    'Saudi Arabia': 'sa',
    'Sweden': 'se',
    'Singapore': 'sg',
    'Spain': 'es',
    'South Africa': 'za',
    'Slovakia': 'sk',
    'Switzerland': 'ch',
    'Thailand': 'th',
    'Turkey': 'tr',
    'Taiwan': 'tw',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom': 'gb',
    'United States': 'us',
    'Uruguay': 'uy',
    'Vietnam': 'vn',
  };

  // supported local charts and their codes
  static const Map<String, String> localChartCodes = {
    'Global': '37i9dQZEVXbMDoHDwVN2tF',
    'Argentina': '37i9dQZEVXbMMy2roB9myp',
    'Australia': '37i9dQZEVXbJPcfkRz0wJ0',
    'Austria': '37i9dQZEVXbKNHh6NIXu36',
    'Belarus': '37i9dQZEVXbIYfjSLbWr4V',
    'Belgium': '37i9dQZEVXbJNSeeHswcKB',
    'Bolivia': '37i9dQZEVXbJqfMFK4d691',
    'Brazil': '37i9dQZEVXbMXbN3EUUhlg',
    'Bulgaria': '37i9dQZEVXbNfM2w2mq1B8',
    'Canada': '37i9dQZEVXbKj23U1GF4IR',
    'Chile': '37i9dQZEVXbL0GavIqMTeb',
    'Colombia': '37i9dQZEVXbOa2lmxNORXQ',
    'Costa Rica': '37i9dQZEVXbMZAjGMynsQX',
    'Czeck Republic': '37i9dQZEVXbIP3c3fqVrJY',
    'Denmark': '37i9dQZEVXbL3J0k32lWnN',
    'Dominican Republic': '37i9dQZEVXbKAbrMR8uuf7',
    'Ecuador': '37i9dQZEVXbJlM6nvL1nD1',
    'Egypt': '37i9dQZEVXbJqdarpmTJDL',
    'El Salvador': '37i9dQZEVXbLxoIml4MYkT',
    'Estonia': '37i9dQZEVXbLesry2Qw2xS',
    'Finland': '37i9dQZEVXbMxcczTSoGwZ',
    'France': '37i9dQZEVXbIPWwFssbupI',
    'Germany': '37i9dQZEVXbJiZcmkrIHGU',
    'Greece': '37i9dQZEVXbJqdarpmTJDL',
    'Guatemala': '37i9dQZEVXbLy5tBFyQvd4',
    'Honduras': '37i9dQZEVXbJp9wcIM9Eo5',
    'Hong Kong': '37i9dQZEVXbLwpL8TjsxOG',
    'Hungary': '37i9dQZEVXbNHwMxAkvmF8',
    'Iceland': '37i9dQZEVXbKMzVsSGQ49S',
    'India': '37i9dQZEVXbLZ52XmnySJg',
    'Indonesia': '37i9dQZEVXbObFQZ3JLcXt',
    'Ireland': '37i9dQZEVXbKM896FDX8L1',
    'Israel': '37i9dQZEVXbJ6IpvItkve3',
    'Italy': '37i9dQZEVXbIQnj7RRhdSX',
    'Japan': '37i9dQZEVXbKXQ4mDTEBXq',
    'Kazakhstan': '37i9dQZEVXbM472oKPNKzS',
    'Latvia': '37i9dQZEVXbJWuzDrTxbKS',
    'Lithuania': '37i9dQZEVXbMx56Rdq5lwc',
    'Luxembourg': '37i9dQZEVXbKGcyg6TFGx6',
    'Malaysia': '37i9dQZEVXbJlfUljuZExa',
    'Mexico': '37i9dQZEVXbO3qyFxbkOE1',
    'Morocco': '37i9dQZEVXbJqdarpmTJDL',
    'Netherlands': '37i9dQZEVXbKCF6dqVpDkS',
    'New Zealand': '37i9dQZEVXbM8SIrkERIYl',
    'Nicaragua': '37i9dQZEVXbISk8kxnzfCq',
    'Nigeria': '37i9dQZEVXbKY7jLzlJ11V',
    'Norway': '37i9dQZEVXbJvfa0Yxg7E7',
    'Pakistan': '37i9dQZEVXbJkgIdfsJyTw',
    'Panama': '37i9dQZEVXbKypXHVwk1f0',
    'Paraguay': '37i9dQZEVXbNOUPGj7tW6T',
    'Peru': '37i9dQZEVXbJfdy5b0KP7W',
    'Philippines': '37i9dQZEVXbNBz9cRCSFkY',
    'Poland': '37i9dQZEVXbN6itCcaL3Tt',
    'Portugal': '37i9dQZEVXbKyJS56d1pgi',
    'Romania': '37i9dQZEVXbNZbJ6TZelCq',
    'Saudi Arabia': '37i9dQZEVXbLrQBcXqUtaC',
    'Singapore': '37i9dQZEVXbK4gjvS1FjPY',
    'Slovakia': '37i9dQZEVXbKIVTPX9a2Sb',
    'South Africa': '37i9dQZEVXbMH2jvi6jvjk',
    'South Korea': '37i9dQZEVXbNxXF4SkHj9F',
    'Spain': '37i9dQZEVXbNFJfN1Vw8d9',
    'Sweden': '37i9dQZEVXbLoATJ81JYXz',
    'Switzerland': '37i9dQZEVXbJiyhoAPEfMK',
    'Taiwan': '37i9dQZEVXbMnZEatlMSiu',
    'Thailand': '37i9dQZEVXbMnz8KIWsvf9',
    'Turkey': '37i9dQZEVXbIVYVBNw9D5K',
    'Ukraine': '37i9dQZEVXbKkidEfWYRuD',
    'UAE': '37i9dQZEVXbM4UZuIrvHvA',
    'United Kingdom': '37i9dQZEVXbLnolsZ8PSNw',
    'USA': '37i9dQZEVXbLRQDuF5jeBp',
    'Uruguay': '37i9dQZEVXbMJJi3wgRbAy',
    'Venezuela': '37i9dQZEVXbJ6IpvItkve3',
    'Vietnam': '37i9dQZEVXbLdGSmz6xilI',
  };

static List<Map<String, String>> countries = [
  {'name': 'Afghanistan', 'code': 'AF'},
  {'name': 'Albania', 'code': 'AL'},
  {'name': 'Algeria', 'code': 'DZ'},
  {'name': 'Andorra', 'code': 'AD'},
  {'name': 'Angola', 'code': 'AO'},
  {'name': 'Antigua and Barbuda', 'code': 'AG'},
  {'name': 'Argentina', 'code': 'AR'},
  {'name': 'Armenia', 'code': 'AM'},
  {'name': 'Australia', 'code': 'AU'},
  {'name': 'Austria', 'code': 'AT'},
  {'name': 'Azerbaijan', 'code': 'AZ'},
  {'name': 'Bahamas', 'code': 'BS'},
  {'name': 'Bahrain', 'code': 'BH'},
  {'name': 'Bangladesh', 'code': 'BD'},
  {'name': 'Barbados', 'code': 'BB'},
  {'name': 'Belarus', 'code': 'BY'},
  {'name': 'Belgium', 'code': 'BE'},
  {'name': 'Belize', 'code': 'BZ'},
  {'name': 'Benin', 'code': 'BJ'},
  {'name': 'Bhutan', 'code': 'BT'},
  {'name': 'Bolivia', 'code': 'BO'},
  {'name': 'Bosnia and Herzegovina', 'code': 'BA'},
  {'name': 'Botswana', 'code': 'BW'},
  {'name': 'Brazil', 'code': 'BR'},
  {'name': 'Brunei', 'code': 'BN'},
  {'name': 'Bulgaria', 'code': 'BG'},
  {'name': 'Burkina Faso', 'code': 'BF'},
  {'name': 'Burundi', 'code': 'BI'},
  {'name': 'Cabo Verde', 'code': 'CV'},
  {'name': 'Cambodia', 'code': 'KH'},
  {'name': 'Cameroon', 'code': 'CM'},
  {'name': 'Canada', 'code': 'CA'},
  {'name': 'Central African Republic', 'code': 'CF'},
  {'name': 'Chad', 'code': 'TD'},
  {'name': 'Chile', 'code': 'CL'},
  {'name': 'China', 'code': 'CN'},
  {'name': 'Colombia', 'code': 'CO'},
  {'name': 'Comoros', 'code': 'KM'},
  {'name': 'Congo (Congo-Brazzaville)', 'code': 'CG'},
  {'name': 'Costa Rica', 'code': 'CR'},
  {'name': 'Croatia', 'code': 'HR'},
  {'name': 'Cuba', 'code': 'CU'},
  {'name': 'Cyprus', 'code': 'CY'},
  {'name': 'Czechia (Czech Republic)', 'code': 'CZ'},
  {'name': 'Democratic Republic of the Congo', 'code': 'CD'},
  {'name': 'Denmark', 'code': 'DK'},
  {'name': 'Djibouti', 'code': 'DJ'},
  {'name': 'Dominica', 'code': 'DM'},
  {'name': 'Dominican Republic', 'code': 'DO'},
  {'name': 'Ecuador', 'code': 'EC'},
  {'name': 'Egypt', 'code': 'EG'},
  {'name': 'El Salvador', 'code': 'SV'},
  {'name': 'Equatorial Guinea', 'code': 'GQ'},
  {'name': 'Eritrea', 'code': 'ER'},
  {'name': 'Estonia', 'code': 'EE'},
  {'name': 'Eswatini (fmr. "Swaziland")', 'code': 'SZ'},
  {'name': 'Ethiopia', 'code': 'ET'},
  {'name': 'Fiji', 'code': 'FJ'},
  {'name': 'Finland', 'code': 'FI'},
  {'name': 'France', 'code': 'FR'},
  {'name': 'Gabon', 'code': 'GA'},
  {'name': 'Gambia', 'code': 'GM'},
  {'name': 'Georgia', 'code': 'GE'},
  {'name': 'Germany', 'code': 'DE'},
  {'name': 'Ghana', 'code': 'GH'},
  {'name': 'Greece', 'code': 'GR'},
  {'name': 'Grenada', 'code': 'GD'},
  {'name': 'Guatemala', 'code': 'GT'},
  {'name': 'Guinea', 'code': 'GN'},
  {'name': 'Guinea-Bissau', 'code': 'GW'},
  {'name': 'Guyana', 'code': 'GY'},
  {'name': 'Haiti', 'code': 'HT'},
  {'name': 'Holy See', 'code': 'VA'},
  {'name': 'Honduras', 'code': 'HN'},
  {'name': 'Hungary', 'code': 'HU'},
  {'name': 'Iceland', 'code': 'IS'},
  {'name': 'India', 'code': 'IN'},
  {'name': 'Indonesia', 'code': 'ID'},
  {'name': 'Iran', 'code': 'IR'},
  {'name': 'Iraq', 'code': 'IQ'},
  {'name': 'Ireland', 'code': 'IE'},
  {'name': 'Israel', 'code': 'IL'},
  {'name': 'Italy', 'code': 'IT'},
  {'name': 'Jamaica', 'code': 'JM'},
  {'name': 'Japan', 'code': 'JP'},
  {'name': 'Jordan', 'code': 'JO'},
  {'name': 'Kazakhstan', 'code': 'KZ'},
  {'name': 'Kenya', 'code': 'KE'},
  {'name': 'Kiribati', 'code': 'KI'},
  {'name': 'Kuwait', 'code': 'KW'},
  {'name': 'Kyrgyzstan', 'code': 'KG'},
  {'name': 'Laos', 'code': 'LA'},
  {'name': 'Latvia', 'code': 'LV'},
  {'name': 'Lebanon', 'code': 'LB'},
  {'name': 'Lesotho', 'code': 'LS'},
  {'name': 'Liberia', 'code': 'LR'},
  {'name': 'Libya', 'code': 'LY'},
  {'name': 'Liechtenstein', 'code': 'LI'},
  {'name': 'Lithuania', 'code': 'LT'},
  {'name': 'Luxembourg', 'code': 'LU'},
  {'name': 'Madagascar', 'code': 'MG'},
  {'name': 'Malawi', 'code': 'MW'},
  {'name': 'Malaysia', 'code': 'MY'},
  {'name': 'Maldives', 'code': 'MV'},
  {'name': 'Mali', 'code': 'ML'},
  {'name': 'Malta', 'code': 'MT'},
  {'name': 'Marshall Islands', 'code': 'MH'},
  {'name': 'Mauritania', 'code': 'MR'},
  {'name': 'Mauritius', 'code': 'MU'},
  {'name': 'Mexico', 'code': 'MX'},
  {'name': 'Micronesia', 'code': 'FM'},
  {'name': 'Moldova', 'code': 'MD'},
  {'name': 'Monaco', 'code': 'MC'},
  {'name': 'Mongolia', 'code': 'MN'},
  {'name': 'Montenegro', 'code': 'ME'},
  {'name': 'Morocco', 'code': 'MA'},
  {'name': 'Mozambique', 'code': 'MZ'},
  {'name': 'Myanmar (formerly Burma)', 'code': 'MM'},
  {'name': 'Namibia', 'code': 'NA'},
  {'name': 'Nauru', 'code': 'NR'},
  {'name': 'Nepal', 'code': 'NP'},
  {'name': 'Netherlands', 'code': 'NL'},
  {'name': 'New Zealand', 'code': 'NZ'},
  {'name': 'Nicaragua', 'code': 'NI'},
  {'name': 'Niger', 'code': 'NE'},
  {'name': 'Nigeria', 'code': 'NG'},
  {'name': 'North Korea', 'code': 'KP'},
  {'name': 'North Macedonia (formerly Macedonia)', 'code': 'MK'},
  {'name': 'Norway', 'code': 'NO'},
  {'name': 'Oman', 'code': 'OM'},
  {'name': 'Pakistan', 'code': 'PK'},
  {'name': 'Palau', 'code': 'PW'},
  {'name': 'Palestine State', 'code': 'PS'},
  {'name': 'Panama', 'code': 'PA'},
  {'name': 'Papua New Guinea', 'code': 'PG'},
  {'name': 'Paraguay', 'code': 'PY'},
  {'name': 'Peru', 'code': 'PE'},
  {'name': 'Philippines', 'code': 'PH'},
  {'name': 'Poland', 'code': 'PL'},
  {'name': 'Portugal', 'code': 'PT'},
  {'name': 'Qatar', 'code': 'QA'},
  {'name': 'Romania', 'code': 'RO'},
  {'name': 'Russia', 'code': 'RU'},
  {'name': 'Rwanda', 'code': 'RW'},
  {'name': 'Saint Kitts and Nevis', 'code': 'KN'},
  {'name': 'Saint Lucia', 'code': 'LC'},
  {'name': 'Saint Vincent and the Grenadines', 'code': 'VC'},
  {'name': 'Samoa', 'code': 'WS'},
  {'name': 'San Marino', 'code': 'SM'},
  {'name': 'Sao Tome and Principe', 'code': 'ST'},
  {'name': 'Saudi Arabia', 'code': 'SA'},
  {'name': 'Senegal', 'code': 'SN'},
  {'name': 'Serbia', 'code': 'RS'},
  {'name': 'Seychelles', 'code': 'SC'},
  {'name': 'Sierra Leone', 'code': 'SL'},
  {'name': 'Singapore', 'code': 'SG'},
  {'name': 'Slovakia', 'code': 'SK'},
  {'name': 'Slovenia', 'code': 'SI'},
  {'name': 'Solomon Islands', 'code': 'SB'},
  {'name': 'Somalia', 'code': 'SO'},
  {'name': 'South Africa', 'code': 'ZA'},
  {'name': 'South Korea', 'code': 'KR'},
  {'name': 'South Sudan', 'code': 'SS'},
  {'name': 'Spain', 'code': 'ES'},
  {'name': 'Sri Lanka', 'code': 'LK'},
  {'name': 'Sudan', 'code': 'SD'},
  {'name': 'Suriname', 'code': 'SR'},
  {'name': 'Sweden', 'code': 'SE'},
  {'name': 'Switzerland', 'code': 'CH'},
  {'name': 'Syria', 'code': 'SY'},
  {'name': 'Tajikistan', 'code': 'TJ'},
  {'name': 'Tanzania', 'code': 'TZ'},
  {'name': 'Thailand', 'code': 'TH'},
  {'name': 'Timor-Leste', 'code': 'TL'},
  {'name': 'Togo', 'code': 'TG'},
  {'name': 'Tonga', 'code': 'TO'},
  {'name': 'Trinidad and Tobago', 'code': 'TT'},
  {'name': 'Tunisia', 'code': 'TN'},
  {'name': 'Turkey', 'code': 'TR'},
  {'name': 'Turkmenistan', 'code': 'TM'},
  {'name': 'Tunisia', 'code': 'TN'},
  {'name': 'Turkey', 'code': 'TR'},
  {'name': 'Turkmenistan', 'code': 'TM'},
  {'name': 'Tuvalu', 'code': 'TV'},
  {'name': 'Uganda', 'code': 'UG'},
  {'name': 'Ukraine', 'code': 'UA'},
  {'name': 'United Arab Emirates', 'code': 'AE'},
  {'name': 'United Kingdom', 'code': 'GB'},
  {'name': 'United States of America', 'code': 'US'},
  {'name': 'Uruguay', 'code': 'UY'},
  {'name': 'Uzbekistan', 'code': 'UZ'},
  {'name': 'Vanuatu', 'code': 'VU'},
  {'name': 'Venezuela', 'code': 'VE'},
  {'name': 'Vietnam', 'code': 'VN'},
  {'name': 'Yemen', 'code': 'YE'},
  {'name': 'Zambia', 'code': 'ZM'},
  {'name': 'Zimbabwe', 'code': 'ZW'},
];
}

